In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("bases_de_dados/Sivep/bases_novas/not_encoded/severity/sivep_kids_atualizado_not_encoded_severity_reduced_doctors.csv")
#df['UTI'] = df['UTI'].map({'nao':'nao', 'sim':'sim', 'ignorado':'nao'})
df['Doses_vacina'] = df['Doses_vacina'].map({'zero': 'zero', 'uma':'uma', 'duas':'duas', 'tres':'tres','missing':'zero'})

In [3]:
from pycaret.classification import *
s = setup(df, target = 'outcome_geral_severe', session_id = 11, 
          log_experiment = True, experiment_name = 'sev_3', max_encoding_ohe=100)

In [4]:
best = compare_models(exclude=['lightgbm', 'ridge', 'svm', 'dummy'])