In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv("bases_de_dados/Sivep/bases_novas/not_encoded/sivep_kids_atualizado_not_encoded_reduced_evo.csv")

In [5]:
df.drop(df[df['outcome_final_SIVEP'] == "in-hospital"].index, inplace = True)
df['Doses_vacina'] = df['Doses_vacina'].map({'zero': 'zero', 'uma':'uma', 'duas':'duas', 'tres':'tres','missing':'zero'})
df['Doses_vacina'].value_counts()

zero    20184
duas     1122
uma       779
tres      168
Name: Doses_vacina, dtype: int64

In [6]:
df['outcome_final_SIVEP'].value_counts()

discharge    20742
death         1511
Name: outcome_final_SIVEP, dtype: int64

In [170]:
df.head()

,gender,idade_anos,etnia,region,Virus_strain,dyspnea,fever,cough,odynophagia,abdominal_Pain,ageusia,anosmia,REspDistress,Oxygen_saturation_reduced,comorbidades_total,outcome_final_SIVEP,Doses_vacina,nosocomial
0,male,17.000000,Brown,Northeast,gamma,sim,nao,nao,nao,nao,nao,nao,sim,sim,0.0,death,zero,nao
1,male,16.416667,White,South,delta,nao,sim,sim,nao,nao,nao,nao,sim,sim,3.0,death,zero,nao
2,male,15.333333,Brown,Southeast,gamma,nao,sim,sim,nao,nao,nao,nao,nao,nao,0.0,death,zero,nao
3,male,14.333333,White,Southeast,gamma,sim,sim,nao,nao,nao,nao,nao,sim,nao,0.0,death,zero,nao
4,male,13.583333,White,North,omicron,sim,nao,nao,nao,nao,sim,nao,sim,sim,0.0,death,zero,nao

In [175]:
from pycaret.classification import *
s = setup(df, target = 'outcome_final_SIVEP', session_id = 123, 
          log_experiment = True, experiment_name = 'evo_1', remove_multicollinearity = True, max_encoding_ohe=100, fix_imbalance=True, fix_imbalance_method="SMOTEENN")

In [76]:
get_config()

{'USI',
 'X',
 'X_test',
 'X_test_transformed',
 'X_train',
 'X_train_transformed',
 'X_transformed',
 '_available_plots',
 '_ml_usecase',
 'data',
 'dataset',
 'dataset_transformed',
 'exp_id',
 'exp_name_log',
 'fix_imbalance',
 'fold_generator',
 'fold_groups_param',
 'fold_shuffle_param',
 'gpu_n_jobs_param',
 'gpu_param',
 'html_param',
 'idx',
 'is_multiclass',
 'log_plots_param',
 'logging_param',
 'memory',
 'n_jobs_param',
 'pipeline',
 'seed',
 'target_param',
 'test',
 'test_transformed',
 'train',
 'train_transformed',
 'variable_and_property_keys',
 'variables',
 'y',
 'y_test',
 'y_test_transformed',
 'y_train',
 'y_train_transformed',
 'y_transformed'}

In [183]:
get_config('X_transformed').tail()

,gender,idade_anos,etnia_White,etnia_Brown,etnia_Indigenous,etnia_Black,etnia_Asian,region_Southeast,region_South,region_Central_West,...,ageusia,anosmia,REspDistress,Oxygen_saturation_reduced,comorbidades_total,Doses_vacina_zero,Doses_vacina_uma,Doses_vacina_duas,Doses_vacina_tres,nosocomial
7542,1.0,1.000000,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
10569,1.0,1.250000,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
22777,0.0,11.500000,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
24031,0.0,2.166667,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
5261,1.0,1.000000,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0

In [182]:
best = compare_models(exclude=['lightgbm', 'ridge', 'svm', 'dummy'])

In [180]:
best.get_params()

{'constant': None, 'random_state': 123, 'strategy': 'prior'}

In [168]:
cat = create_model('catboost')

In [169]:
evaluate_model(cat)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [71]:
data_transf = get_config('data')

In [72]:
data_transf.tail()

,gender,idade_anos,idade_cat_3,idade_cat_4,etnia,region,Virus_strain,dyspnea,fever,cough,...,codigoRecebeuVacina,Doses_vacina,hematology,neurology,oncology,Transplant,sind_down,syndrome,nosocomial,outcome_final_SIVEP
7542,male,1.000000,<2,<2,Brown,Southeast,gamma,sim,sim,sim,...,nao,zero,nao,sim,nao,nao,nao,nao,nao,discharge
10569,male,1.250000,<2,<2,Brown,Northeast,omicron,sim,nao,sim,...,nao,zero,nao,nao,nao,nao,nao,nao,nao,discharge
22777,female,11.500000,2-11,5-11,White,South,gamma,sim,sim,sim,...,nao,zero,nao,nao,nao,nao,nao,nao,nao,discharge
24031,female,2.166667,2-11,2-4,White,South,omicron,nao,sim,nao,...,nao,zero,nao,nao,nao,nao,nao,nao,nao,discharge
5261,male,1.000000,<2,<2,White,Southeast,omicron,sim,nao,sim,...,nao,zero,nao,nao,nao,nao,nao,nao,nao,discharge

In [ ]:
model_data = class_df.sample(frac=0.9, random_state=786)
data_unseen = class_df.drop(model_data.index)

model_data.reset_index(drop=True, inplace=True)
data_unseen.reset_index(drop=True, inplace=True)

print('Data for Modeling: ' + str(model_data.shape))
print('Unseen Data For Predictions: ' + str(data_unseen.shape))

In [138]:
tuned_gbc = tune_model(gbc)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [135]:
print(gbc)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=123, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [136]:
print(tuned_gbc)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=123, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [141]:
calibrated_gbc = calibrate_model(tuned_gbc)

In [142]:
interpret_model(tuned_gbc)

TypeError: This function only supports tree based models for binary classification: xgboost, catboost, dt, et, lightgbm, rf.