In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("bases_de_dados/Sivep/bases_novas/not_encoded/uti/sivep_kids_atualizado_not_encoded_uti_reduced_doctors.csv")
df['UTI'] = df['UTI'].map({'nao':'nao', 'sim':'sim', 'ignorado':'nao'})
df['Doses_vacina'] = df['Doses_vacina'].map({'zero': 'zero', 'uma':'uma', 'duas':'duas', 'tres':'tres','missing':'zero'})

In [2]:
from pycaret.classification import *
s = setup(df, target = 'UTI', session_id = 3, 
          log_experiment = True, experiment_name = 'UTI_2', remove_multicollinearity = True, max_encoding_ohe=100)

In [3]:
best = compare_models(exclude=['lightgbm','ridge', 'svm', 'dummy'])