In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv("bases_de_dados/Sivep/bases_novas/not_encoded/uti/sivep_kids_atualizado_not_encoded_uti_reduced_by_chi.csv")
df['UTI'] = df['UTI'].map({'nao':'nao', 'sim':'sim', 'ignorado':'nao'})
#df['Doses_vacina'] = df['Doses_vacina'].map({'zero': 'zero', 'uma':'uma', 'duas':'duas', 'tres':'tres','missing':'zero'})

In [3]:
df['UTI'].value_counts()

nao    17949
sim     6148
Name: UTI, dtype: int64

In [4]:
from pycaret.classification import *
s = setup(df, target = 'UTI', session_id = 4, 
          log_experiment = True, experiment_name = 'UTI_3', max_encoding_ohe=100)

In [5]:
best = compare_models(exclude=['lightgbm','ridge', 'svm', 'dummy'])

In [4]:
df['UTI'].value_counts()

nao    17949
sim     6148
Name: UTI, dtype: int64